### ISSUE TITLE
Newly created views do not have event handlers

### ISSUE THREAD

**Issue by dagda1** [joneath/infiniScroll.js#2]
Hi,

I am using the plugin and love it with one exception.

My event handlers do not work for the newly fetched views?  

By event handlers I mean events defined in the view event hash.  

Is this something you have experienced ?

**Comment by joneath** [comment]
Interesting, I would think the event delegation should still work for the newly injected content, but you could try calling delegateEvents after you do the append render.

 So something like this

```
    appendRender: function(collection) {
        // append the new content

        this.delegateEvents(this.events);
    }
```
